[package]
name = "pg_graphql"
version = "0.5.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg14"]
pg14 = ["pgx/pg14", "pgx-tests/pg14"]
pg15 = ["pgx/pg15", "pgx-tests/pg15"]
pg_test = []

[dependencies]
pgx = "~0.6.1"
graphql-parser = "0.4"
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0"
itertools = "0.10.3"
cached = "0.34.0"
rand = "0.8"
uuid = "1"
regex = "1"
base64 = "0.13"
lazy_static = "1"
pgx-contrib-spiext = { git = "https://github.com/supabase/pgx-contrib-spiext", rev = "153ad2db8bb8634332ad36ffc66dcb017353bf93" }
quick_cache = "0.1.1"

[dev-dependencies]
pgx-tests = "~0.6.1"

[profile.dev]
panic = "unwind"
lto = "thin"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
