site_name: pg_graphql
site_url: https://supabase.github.io/pg_graphql
site_description: A PostgreSQL extension adding GraphQL support

repo_name: supabase/pg_graphql
repo_url: https://github.com/supabase/pg_graphql

nav:
    - Welcome: 'index.md'
    - Quickstart: 'quickstart.md'
    - SQL Interface: 'sql_interface.md'
    - API: 'api.md'
    - Views: 'views.md'
    - Functions: 'functions.md'
    - Computed Fields: 'computed_fields.md'
    - Security: 'security.md'
    - Configuration: 'configuration.md'
    - Guides:
      - Supabase: 'supabase.md'
      - Usage with Relay: 'usage_with_relay.md'
    - Example Schema: 'example_schema.md'
    - Installation: 'installation.md'
    - Contributing: 'contributing.md'
    - Changelog: 'changelog.md'

theme:
    name: 'material'
    features:
      - navigation.expand
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/pg_graphql
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
